// ---------------------------------------------------------------------
// The scorecard: each strategy's trajectory as numbers it can be held to
// (test/balance-scorecard.test.ts fails on either kind of band).
//
// TARGETS are hand-written: where the game should be, for the Balanced
// builder and the two controls. REFERENCE is generated by `npm run sim --
// --write-reference`: where every other strategy is, the envelope of three
// seeds at +/-TOLERANCE, so a change that moves a trajectory is noticed.
//
// Not part of the game: nothing in src/ imports this.
// ---------------------------------------------------------------------

import type { Row } from './balanceSim';

// The years a trajectory is read at, across the three eras: found (1-12),
// build (12-35), defend (35-50).
export const REFERENCE_YEARS = [5, 10, 20, 35, 50] as const;
export const REFERENCE_HORIZON = 50;

// The two extra streams `--write-reference` plays beside the default seed,
// so a band is the envelope of several runs rather than a claim about one.
export const REFERENCE_EXTRA_SEEDS = [4242, 777];

// And another founding name, at the default seed (Plan 49). Program offers
// are seeded from the college's name (programOffers.ts), so the name is a
// second stream: on one name the Balanced builder once stalled for a decade
// while its seeds all grew.
export const REFERENCE_EXTRA_NAMES = ['Harrow College'];

// Every run a band or a gate is judged across: the default, then the extra
// seeds, then the extra names.
export interface RunKey { seed?: number; name?: string }
export const REFERENCE_RUNS: RunKey[] = [
  {},
  ...REFERENCE_EXTRA_SEEDS.map((seed) => ({ seed })),
  ...REFERENCE_EXTRA_NAMES.map((name) => ({ name })),
];

// How far either side of the recorded figure still counts as the same run.
// Wide on purpose: the economy is a threshold system, so small changes move
// which week something is built and decades compound it. One tolerance for
// every metric, which is looser on bounded prestige than on cash.
export const TOLERANCE = 0.25;

// A floor on each band's half-width, in the metric's own units, because a
// percentage of a number near zero is no band at all.
const FLOOR: Record<Metric, number> = {
  cash: 1_000_000,      // a million dollars is a rounding error by year 10
  enrolled: 100,        // a hundred students
  prestige: 2,          // two points on a 5..150 scale
  rank: 3,              // three places in a hundred-school field
  netMargin: 0.05,      // five points of margin
  weeksInTheRed: 10,    // ten weeks over the five years a sample covers
};

export type Metric = 'cash' | 'enrolled' | 'prestige' | 'rank' | 'netMargin' | 'weeksInTheRed';

export const METRICS: Metric[] = ['cash', 'enrolled', 'prestige', 'rank', 'netMargin', 'weeksInTheRed'];

export interface Band { lo: number; hi: number }
export type ReferenceRow = { year: number } & Record<Metric, Band>;
export type Reference = Record<string, ReferenceRow[]>;

// The operating margin: the week's net less the endowment payout and the
// annual fund, as a share of weekly operating cost; 0 when opex is 0. The
// metric kept its name when Plan 35 took the endowment out of it (V1-25):
// the headline margin rose to 70% late in a run because the harness moves
// every spare dollar into the endowment, whose payout comes back as income.
// A rows file from before Plan 35 has no payout or fund, and reads as the
// headline margin.
export function netMargin(row: Row): number {
  return row.opex > 0 ? (row.net - (row.payout ?? 0) - (row.fund ?? 0)) / row.opex : 0;
}

export function metricOf(row: Row, metric: Metric): number {
  switch (metric) {
    case 'cash': return row.cash;
    case 'enrolled': return row.enrolled;
    case 'prestige': return row.prestige;
    case 'rank': return row.rank;
    case 'netMargin': return netMargin(row);
    case 'weeksInTheRed': return row.weeksInTheRed;
  }
}

// A band around one figure. Written so a NEGATIVE value bands correctly:
// -14M ±25% is [-17.5M, -10.5M], not the inside-out range the naive
// arithmetic gives.
export function bandAround(value: number, metric: Metric): Band {
  const half = Math.max(Math.abs(value) * TOLERANCE, FLOOR[metric]);
  // Two of the five metrics cannot be negative, and a band whose floor is
  // "-10 weeks in the red" is noise in the file rather than a statement.
  const floorAtZero = metric === 'weeksInTheRed' || metric === 'enrolled';
  if (metric === 'rank') return { lo: Math.max(1, value - half), hi: value + half };
  return { lo: floorAtZero ? Math.max(0, value - half) : value - half, hi: value + half };
}

// The bands a run implies — what `--write-reference` commits.
export function bandsFrom(rows: Row[]): ReferenceRow[] {
  const out: ReferenceRow[] = [];
  for (const year of REFERENCE_YEARS) {
    const row = rows.find((r) => r.year === year);
    if (!row) continue;
    out.push({
      year,
      cash: bandAround(row.cash, 'cash'),
      enrolled: bandAround(row.enrolled, 'enrolled'),
      prestige: bandAround(row.prestige, 'prestige'),
      rank: bandAround(row.rank, 'rank'),
      netMargin: bandAround(netMargin(row), 'netMargin'),
      weeksInTheRed: bandAround(row.weeksInTheRed, 'weeksInTheRed'),
    });
  }
  return out;
}

// The envelope across several runs of one strategy: the lowest low and the
// highest high of the seeds' bands.
export function bandsAcross(runs: Row[][]): ReferenceRow[] {
  const perSeed = runs.map((rows) => bandsFrom(rows));
  const out: ReferenceRow[] = [];
  for (const year of REFERENCE_YEARS) {
    const rows = perSeed.map((bands) => bands.find((r) => r.year === year)).filter((r): r is ReferenceRow => r !== undefined);
    if (rows.length === 0) continue;
    const merged = { year } as ReferenceRow;
    for (const metric of METRICS) {
      merged[metric] = {
        lo: Math.min(...rows.map((r) => r[metric].lo)),
        hi: Math.max(...rows.map((r) => r[metric].hi)),
      };
    }
    out.push(merged);
  }
  return out;
}

// The bands a strategy is held to: a hand-written TARGET where one exists,
// the generated envelope otherwise (see TARGETS below).
export function bandsFor(strategyName: string): ReferenceRow[] | undefined {
  return TARGETS[strategyName] ?? REFERENCE[strategyName];
}

export interface Finding {
  strategy: string;
  year: number;
  metric: Metric;
  value: number;
  band: Band;
  side: 'HIGH' | 'LOW';
}

// Every figure outside its band. A year with no recorded band is skipped:
// an absent band is a missing statement, not a failing one.
export function findingsFor(strategyName: string, rows: Row[]): Finding[] {
  const reference = bandsFor(strategyName);
  if (!reference) return [];
  const findings: Finding[] = [];
  for (const expected of reference) {
    const row = rows.find((r) => r.year === expected.year);
    if (!row) continue;
    for (const metric of METRICS) {
      const value = metricOf(row, metric);
      const band = expected[metric];
      if (value < band.lo) findings.push({ strategy: strategyName, year: expected.year, metric, value, band, side: 'LOW' });
      else if (value > band.hi) findings.push({ strategy: strategyName, year: expected.year, metric, value, band, side: 'HIGH' });
    }
  }
  return findings;
}

function short(n: number, metric: Metric): string {
  if (metric === 'netMargin') return `${(n * 100).toFixed(0)}%`;
  if (metric === 'weeksInTheRed' || metric === 'rank') return n.toFixed(0);
  if (metric === 'prestige') return n.toFixed(1);
  const abs = Math.abs(n);
  const sign = n < 0 ? '-' : '';
  if (abs >= 1e9) return `${sign}${(abs / 1e9).toFixed(2)}B`;
  if (abs >= 1e6) return `${sign}${(abs / 1e6).toFixed(1)}M`;
  if (abs >= 1e3) return `${sign}${(abs / 1e3).toFixed(0)}k`;
  return `${sign}${abs.toFixed(0)}`;
}

// One line per finding, in the shape the plan asked for:
//   year 20 enrolled 42,000 (band 8,000–14,000) HIGH
export function describeFinding(f: Finding): string {
  return `year ${String(f.year).padStart(2)} ${f.metric.padEnd(13)} `
    + `${short(f.value, f.metric).padStart(8)} (band ${short(f.band.lo, f.metric)}–${short(f.band.hi, f.metric)}) ${f.side}`;
}

// The generated source of the block below, so `--write-reference` writes
// this file the way a human would have.
export function serialiseReference(reference: Reference): string {
  const round = (n: number) => Number(n.toFixed(4));
  const entries = Object.entries(reference).map(([name, rows]) => {
    const body = rows.map((row) => {
      const fields = METRICS
        .map((m) => `${m}: { lo: ${round(row[m].lo)}, hi: ${round(row[m].hi)} }`)
        .join(', ');
      return `    { year: ${row.year}, ${fields} },`;
    }).join('\n');
    return `  ${JSON.stringify(name)}: [\n${body}\n  ],`;
  }).join('\n');
  return `export const REFERENCE: Reference = {\n${entries}\n};`;
}

// =====================================================================
// TARGETS: where the game should be. Hand-written, never generated, and
// they take precedence over REFERENCE for the strategies they name.
// =====================================================================
//
// - Balanced builder: the design table in docs/plans/15-growth-has-a-cost.md
//   (section 6), re-read for a college that opens teaching, which puts it
//   about a decade ahead of those eras in standing: top fifty by year 5,
//   rank #1 by year 20. Enrollment bands are wide because seeds diverge on
//   when the catalog is finished. Net margin is 25-40% while building and
//   5-15% from year 35, and positive at 50 because a mature builder keeps
//   building (balanceSim.ts's HEADROOM_OPEX_CAP). Cash is loose: "one to
//   three years of surplus" is a relation, not a figure.
// - Idle: a small college that never grows, ten points under its founding
//   standing within five years and held there, at its founding seats.
// - Overbuilder: underwater around year 5 (a coin flip on the seed, so the
//   year-5 row allows "within a million of it"; year 10 requires a red
//   week), then it stalls or keeps sinking depending on the seed. The cash
//   floors at years 20, 35 and 50 cover the sinking seeds;
//   test/balance-regression.test.ts holds the "stall, don't die" claims.
export const TARGETS: Reference = {
  'Balanced builder': [
    { year: 5, cash: { lo: -2_000_000, hi: 20_000_000 }, enrolled: { lo: 1_000, hi: 3_500 }, prestige: { lo: 45, hi: 75 }, rank: { lo: 30, hi: 70 }, netMargin: { lo: 0.1, hi: 0.6 }, weeksInTheRed: { lo: 0, hi: 60 } },
    { year: 10, cash: { lo: -2_000_000, hi: 40_000_000 }, enrolled: { lo: 4_000, hi: 16_000 }, prestige: { lo: 55, hi: 95 }, rank: { lo: 12, hi: 60 }, netMargin: { lo: 0.05, hi: 0.5 }, weeksInTheRed: { lo: 0, hi: 120 } },
    { year: 20, cash: { lo: -5_000_000, hi: 300_000_000 }, enrolled: { lo: 8_000, hi: 32_000 }, prestige: { lo: 80, hi: 140 }, rank: { lo: 1, hi: 20 }, netMargin: { lo: -0.15, hi: 0.4 }, weeksInTheRed: { lo: 0, hi: 200 } },
    { year: 35, cash: { lo: -20_000_000, hi: 2_000_000_000 }, enrolled: { lo: 12_000, hi: 40_000 }, prestige: { lo: 100, hi: 150 }, rank: { lo: 1, hi: 8 }, netMargin: { lo: -0.15, hi: 0.2 }, weeksInTheRed: { lo: 0, hi: 400 } },
    // Years 20, 35 and 50's operating-margin floors were -5% until Plan 36:
    // the cost of being large puts a big college's operating margin a few
    // points under zero, and the endowment's payout carries it.
    // Year 50's margin was read with the endowment's payout in it until
    // Plan 35, and its ceiling had risen to 75% (Plans 29, 30 and 32). The
    // operating margin (netMargin above) is 1–3% from Year 15 on, and the
    // band is the mature college's.
    { year: 50, cash: { lo: -20_000_000, hi: 5_000_000_000 }, enrolled: { lo: 15_000, hi: 42_000 }, prestige: { lo: 110, hi: 150 }, rank: { lo: 1, hi: 5 }, netMargin: { lo: -0.15, hi: 0.2 }, weeksInTheRed: { lo: 0, hi: 500 } },
  ],
  'Idle (builds nothing)': [
    { year: 5, cash: { lo: 0, hi: 50_000_000 }, enrolled: { lo: 0, hi: 480 }, prestige: { lo: 5, hi: 45 }, rank: { lo: 60, hi: 100 }, netMargin: { lo: -1, hi: 3 }, weeksInTheRed: { lo: 0, hi: 100 } },
    { year: 10, cash: { lo: 0, hi: 50_000_000 }, enrolled: { lo: 0, hi: 480 }, prestige: { lo: 5, hi: 44 }, rank: { lo: 60, hi: 100 }, netMargin: { lo: -1, hi: 3 }, weeksInTheRed: { lo: 0, hi: 200 } },
    { year: 20, cash: { lo: 0, hi: 50_000_000 }, enrolled: { lo: 0, hi: 480 }, prestige: { lo: 5, hi: 44 }, rank: { lo: 60, hi: 100 }, netMargin: { lo: -1, hi: 3 }, weeksInTheRed: { lo: 0, hi: 500 } },
    { year: 35, cash: { lo: 0, hi: 50_000_000 }, enrolled: { lo: 0, hi: 480 }, prestige: { lo: 5, hi: 44 }, rank: { lo: 60, hi: 100 }, netMargin: { lo: -1, hi: 3 }, weeksInTheRed: { lo: 0, hi: 1_000 } },
    // Year 50's cash ceiling was $50M until Plan 30: even an idle college's
    // few hundred graduates give to the annual fund ($53M at the default seed).
    { year: 50, cash: { lo: 0, hi: 75_000_000 }, enrolled: { lo: 0, hi: 480 }, prestige: { lo: 5, hi: 44 }, rank: { lo: 60, hi: 100 }, netMargin: { lo: -1, hi: 3 }, weeksInTheRed: { lo: 0, hi: 1_500 } },
  ],
  'Overbuilder (beds ahead of demand)': [
    // Year 5's margin ceiling was 15% and year 35's enrollment ceiling 8,000
    // until Plan 35: on the larger founding gift the overbuilder stalls less,
    // and reads 16% at year 5 and 8,240 students at year 35.
    { year: 5, cash: { lo: -6_000_000, hi: 1_000_000 }, enrolled: { lo: 300, hi: 2_000 }, prestige: { lo: 30, hi: 65 }, rank: { lo: 40, hi: 90 }, netMargin: { lo: -0.5, hi: 0.25 }, weeksInTheRed: { lo: 0, hi: 260 } },
    { year: 10, cash: { lo: -8_000_000, hi: 3_000_000 }, enrolled: { lo: 300, hi: 3_000 }, prestige: { lo: 30, hi: 70 }, rank: { lo: 35, hi: 90 }, netMargin: { lo: -0.5, hi: 0.2 }, weeksInTheRed: { lo: 1, hi: 520 } },
    { year: 20, cash: { lo: -30_000_000, hi: 10_000_000 }, enrolled: { lo: 300, hi: 5_000 }, prestige: { lo: 30, hi: 75 }, rank: { lo: 30, hi: 90 }, netMargin: { lo: -0.4, hi: 0.3 }, weeksInTheRed: { lo: 1, hi: 1_040 } },
    // Years 35 and 50's prestige and margin floors were 30 and -40% until
    // Plan 29: the faculty it hired early retire from year 25 on, into a
    // college in receivership that is also cutting its payroll, and it stalls
    // lower: at 4242 it bottoms out in year 35 at 297 students and prestige
    // 24, and recovers to 407 and 27 by year 50.
    // Plan 31 made building condition a prestige input, and a college in
    // austerity has had its maintenance cut by the board: its buildings run
    // down and its name follows. Year 35's rank ceiling was 90 and year 50's
    // prestige floor 25: at 4242 it reads rank 93 at year 35, and at 777
    // prestige 24 at year 50 (27.6 and 32.1 without the penalty).
    { year: 35, cash: { lo: -40_000_000, hi: 30_000_000 }, enrolled: { lo: 250, hi: 10_000 }, prestige: { lo: 20, hi: 80 }, rank: { lo: 25, hi: 95 }, netMargin: { lo: -0.6, hi: 0.4 }, weeksInTheRed: { lo: 1, hi: 1_820 } },
    { year: 50, cash: { lo: -50_000_000, hi: 60_000_000 }, enrolled: { lo: 300, hi: 10_000 }, prestige: { lo: 20, hi: 85 }, rank: { lo: 20, hi: 90 }, netMargin: { lo: -0.6, hi: 0.5 }, weeksInTheRed: { lo: 1, hi: 2_600 } },
  ],
};

// `--write-reference` rewrites between the markers below. The marker text
// lives in balanceSim.ts as string literals, not as exported constants here:
// a constant declaring a marker would itself match, and the writer would
// overwrite its own declaration.

// --- GENERATED by `npm run sim -- --write-reference`. Do not hand-edit lightly. ---
export const REFERENCE: Reference = {
  "Balanced builder": [
    { year: 5, cash: { lo: 1444966.9896, hi: 4986365.3215 }, enrolled: { lo: 1068, hi: 3500 }, prestige: { lo: 39.886, hi: 79.7013 }, rank: { lo: 33, hi: 68.75 }, netMargin: { lo: 0.2132, hi: 0.5155 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 3837301.4261, hi: 24235182.2645 }, enrolled: { lo: 3066.75, hi: 15077.5 }, prestige: { lo: 46.7923, hi: 105.5074 }, rank: { lo: 13.5, hi: 62.5 }, netMargin: { lo: -0.0103, hi: 0.4044 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: -26539719.4803, hi: 54126934.7256 }, enrolled: { lo: 14640, hi: 30800 }, prestige: { lo: 79.1719, hi: 155.2391 }, rank: { lo: 1, hi: 7 }, netMargin: { lo: -0.1099, hi: 0.1588 }, weeksInTheRed: { lo: 0, hi: 188.75 } },
    { year: 35, cash: { lo: -42298406.0588, hi: 116808845.9446 }, enrolled: { lo: 22320, hi: 39400 }, prestige: { lo: 108.1233, hi: 186.0308 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.0957, hi: 0.0606 }, weeksInTheRed: { lo: 165.75, hi: 370 } },
    { year: 50, cash: { lo: 17431743.0974, hi: 343731139.4263 }, enrolled: { lo: 22800, hi: 41700 }, prestige: { lo: 112.3733, hi: 187.4572 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.1414, hi: -0.0044 }, weeksInTheRed: { lo: 194.25, hi: 448.75 } },
  ],
  "Curriculum rush (overreach)": [
    { year: 5, cash: { lo: -879202.0654, hi: 4437077.7558 }, enrolled: { lo: 780, hi: 3170 }, prestige: { lo: 33.7845, hi: 71.092 }, rank: { lo: 41.25, hi: 72.5 }, netMargin: { lo: 0.1409, hi: 0.727 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: -832653.513, hi: 5066168.7584 }, enrolled: { lo: 1104, hi: 6698.75 }, prestige: { lo: 38.1144, hi: 85.9221 }, rank: { lo: 34.5, hi: 70 }, netMargin: { lo: 0.0964, hi: 0.3879 }, weeksInTheRed: { lo: 0, hi: 23 } },
    { year: 20, cash: { lo: -69287966.0043, hi: 4833757.0339 }, enrolled: { lo: 3615.75, hi: 38800 }, prestige: { lo: 47.7824, hi: 147.1285 }, rank: { lo: 1, hi: 60 }, netMargin: { lo: -0.1632, hi: 0.2204 }, weeksInTheRed: { lo: 0, hi: 73.75 } },
    { year: 35, cash: { lo: -37758534.2404, hi: 790801619.1091 }, enrolled: { lo: 23640, hi: 41900 }, prestige: { lo: 101.5881, hi: 186.3312 }, rank: { lo: 1, hi: 5 }, netMargin: { lo: -0.0806, hi: 0.1469 }, weeksInTheRed: { lo: 108, hi: 313.75 } },
    { year: 50, cash: { lo: 1778920940.3954, hi: 8537320556.7668 }, enrolled: { lo: 25080, hi: 41900 }, prestige: { lo: 112.1839, hi: 187.4662 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.1158, hi: 0.0107 }, weeksInTheRed: { lo: 108, hi: 313.75 } },
  ],
  "Discount volume (beds first)": [
    { year: 5, cash: { lo: -249449.7932, hi: 6663398.0836 }, enrolled: { lo: 660, hi: 2811.25 }, prestige: { lo: 37.987, hi: 81.3617 }, rank: { lo: 35.25, hi: 68.75 }, netMargin: { lo: -0.0918, hi: 0.2549 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: -1668851.4138, hi: 4700604.3861 }, enrolled: { lo: 660, hi: 4287.5 }, prestige: { lo: 43.3702, hi: 85.4432 }, rank: { lo: 30, hi: 66.25 }, netMargin: { lo: -0.1136, hi: 0.2433 }, weeksInTheRed: { lo: 0, hi: 205 } },
    { year: 20, cash: { lo: 2696430.3391, hi: 19854923.5935 }, enrolled: { lo: 1020, hi: 6300 }, prestige: { lo: 53.1431, hi: 101.695 }, rank: { lo: 21, hi: 46.25 }, netMargin: { lo: -0.1714, hi: 0.0457 }, weeksInTheRed: { lo: 54.75, hi: 272.5 } },
    { year: 35, cash: { lo: -7588706.2851, hi: 22200854.3194 }, enrolled: { lo: 2220, hi: 9000 }, prestige: { lo: 53.1343, hi: 105.6664 }, rank: { lo: 21, hi: 62.5 }, netMargin: { lo: -0.1339, hi: 0.0317 }, weeksInTheRed: { lo: 123, hi: 366.25 } },
    { year: 50, cash: { lo: 372060.6581, hi: 26064868.5244 }, enrolled: { lo: 2220, hi: 11300 }, prestige: { lo: 57.1172, hi: 111.5044 }, rank: { lo: 21.75, hi: 52.5 }, netMargin: { lo: -0.1882, hi: -0.0408 }, weeksInTheRed: { lo: 123, hi: 475 } },
  ],
  "Completionist (build everything)": [
    { year: 5, cash: { lo: 1439462.5515, hi: 4888301.9119 }, enrolled: { lo: 1068, hi: 3000 }, prestige: { lo: 39.9767, hi: 80.7643 }, rank: { lo: 35.25, hi: 68.75 }, netMargin: { lo: 0.1656, hi: 0.4964 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 2869639.4083, hi: 13049708.5354 }, enrolled: { lo: 2560.5, hi: 12500 }, prestige: { lo: 48.7227, hi: 102.8256 }, rank: { lo: 15, hi: 58.75 }, netMargin: { lo: 0.0164, hi: 0.2317 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: -22393241.958, hi: 125429950.8569 }, enrolled: { lo: 5340, hi: 32600 }, prestige: { lo: 73.7462, hi: 137.0614 }, rank: { lo: 1, hi: 10 }, netMargin: { lo: -0.0815, hi: 0.08 }, weeksInTheRed: { lo: 0, hi: 56.25 } },
    { year: 35, cash: { lo: 6537487.1242, hi: 81463107.0378 }, enrolled: { lo: 11940, hi: 39700 }, prestige: { lo: 93.376, hi: 184.8181 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.1081, hi: 0.0514 }, weeksInTheRed: { lo: 60, hi: 291.25 } },
    { year: 50, cash: { lo: 35521740.0089, hi: 83486362.7364 }, enrolled: { lo: 21780, hi: 41200 }, prestige: { lo: 107.388, hi: 187.4224 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.1369, hi: 0.0083 }, weeksInTheRed: { lo: 60, hi: 385 } },
  ],
  "Overbuilder (beds ahead of demand)": [
    { year: 5, cash: { lo: -7205573.0123, hi: 519531.7113 }, enrolled: { lo: 840, hi: 1700 }, prestige: { lo: 30.2674, hi: 79.3014 }, rank: { lo: 35.25, hi: 77.5 }, netMargin: { lo: -0.1187, hi: 0.2155 }, weeksInTheRed: { lo: 30, hi: 192.5 } },
    { year: 10, cash: { lo: -3770809.5255, hi: 3784916.006 }, enrolled: { lo: 720.75, hi: 2157.5 }, prestige: { lo: 28.6456, hi: 78.7649 }, rank: { lo: 36.75, hi: 81.25 }, netMargin: { lo: -0.2215, hi: 0.102 }, weeksInTheRed: { lo: 87, hi: 517.5 } },
    { year: 20, cash: { lo: -11739577.5153, hi: 1606632.8272 }, enrolled: { lo: 530.25, hi: 2700 }, prestige: { lo: 25.0187, hi: 80.0296 }, rank: { lo: 32.25, hi: 92.5 }, netMargin: { lo: -0.2721, hi: 0.1821 }, weeksInTheRed: { lo: 272.25, hi: 876.25 } },
    { year: 35, cash: { lo: -25261872.1267, hi: 3373684.9073 }, enrolled: { lo: 424.5, hi: 5943.75 }, prestige: { lo: 22.813, hi: 77.2542 }, rank: { lo: 42, hi: 106.25 }, netMargin: { lo: -0.3744, hi: 0.0543 }, weeksInTheRed: { lo: 528, hi: 1767.5 } },
    { year: 50, cash: { lo: -12909292.0349, hi: 679434.4205 }, enrolled: { lo: 702, hi: 11410 }, prestige: { lo: 28.5761, hi: 87.1377 }, rank: { lo: 29.25, hi: 90 }, netMargin: { lo: -0.1652, hi: 0.0016 }, weeksInTheRed: { lo: 755.25, hi: 2742.5 } },
  ],
  "Earnest completionist": [
    { year: 5, cash: { lo: 1839291.3436, hi: 4603984.3289 }, enrolled: { lo: 2863.5, hi: 6100 }, prestige: { lo: 42.5686, hi: 84.5918 }, rank: { lo: 33.75, hi: 67.5 }, netMargin: { lo: 0.2462, hi: 0.7145 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 4339341.8894, hi: 34752699.7946 }, enrolled: { lo: 10380, hi: 23900 }, prestige: { lo: 61.3891, hi: 113.6199 }, rank: { lo: 8, hi: 22.5 }, netMargin: { lo: -0.0574, hi: 0.0855 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: -151941963.2865, hi: 30903157.1596 }, enrolled: { lo: 10380, hi: 24500 }, prestige: { lo: 85.509, hi: 158.3712 }, rank: { lo: 1, hi: 5 }, netMargin: { lo: -0.0603, hi: 0.0577 }, weeksInTheRed: { lo: 82.5, hi: 526.25 } },
    { year: 35, cash: { lo: 13189269.935, hi: 58814074.8527 }, enrolled: { lo: 12120, hi: 37700 }, prestige: { lo: 90.5519, hi: 177.3537 }, rank: { lo: 1, hi: 6 }, netMargin: { lo: -0.1185, hi: 0.0484 }, weeksInTheRed: { lo: 82.5, hi: 792.5 } },
    { year: 50, cash: { lo: 17019297.6137, hi: 96731343.91 }, enrolled: { lo: 16620, hi: 39000 }, prestige: { lo: 108.9892, hi: 187.2063 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.1033, hi: 0.0001 }, weeksInTheRed: { lo: 125.25, hi: 792.5 } },
  ],
  "Scatterer (founds anything anywhere)": [
    { year: 5, cash: { lo: 1934101.6712, hi: 6799716.2155 }, enrolled: { lo: 1122.75, hi: 3858.75 }, prestige: { lo: 40.5511, hi: 79.3179 }, rank: { lo: 36.75, hi: 67.5 }, netMargin: { lo: 0.1715, hi: 0.5497 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 4332643.319, hi: 22625195.3928 }, enrolled: { lo: 4028.25, hi: 12855 }, prestige: { lo: 49.8718, hi: 95.553 }, rank: { lo: 24.75, hi: 55 }, netMargin: { lo: 0.0775, hi: 0.3123 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: 4725872.4472, hi: 58675128.9844 }, enrolled: { lo: 9240, hi: 32200 }, prestige: { lo: 68.0281, hi: 125.8618 }, rank: { lo: 1, hi: 15 }, netMargin: { lo: -0.0634, hi: 0.0952 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 35, cash: { lo: 32035694.5315, hi: 181466098.8245 }, enrolled: { lo: 20460, hi: 34600 }, prestige: { lo: 76.2833, hi: 136.9588 }, rank: { lo: 1, hi: 13 }, netMargin: { lo: -0.0756, hi: 0.0523 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 50, cash: { lo: 108297880.9749, hi: 262390758.8549 }, enrolled: { lo: 20580, hi: 34700 }, prestige: { lo: 78.6594, hi: 144.7065 }, rank: { lo: 1, hi: 16.25 }, netMargin: { lo: -0.0814, hi: 0.0413 }, weeksInTheRed: { lo: 0, hi: 10 } },
  ],
  "Selective college": [
    { year: 5, cash: { lo: 11840.566, hi: 4083881.8945 }, enrolled: { lo: 345, hi: 1207.5 }, prestige: { lo: 41.6723, hi: 85.8673 }, rank: { lo: 33, hi: 68.75 }, netMargin: { lo: 0.0451, hi: 0.724 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 3070934.6139, hi: 8496329.3937 }, enrolled: { lo: 885.75, hi: 4706.25 }, prestige: { lo: 49.4832, hi: 100.537 }, rank: { lo: 15.75, hi: 60 }, netMargin: { lo: 0.2966, hi: 0.638 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: 9418028.599, hi: 49617485.951 }, enrolled: { lo: 3157.5, hi: 7295 }, prestige: { lo: 92.6903, hi: 176.418 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.1212, hi: 0.174 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 35, cash: { lo: 12709969.627, hi: 49475183.2204 }, enrolled: { lo: 2992.5, hi: 5046.25 }, prestige: { lo: 111.9265, hi: 187.1792 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.0531, hi: 0.1683 }, weeksInTheRed: { lo: 0, hi: 157.5 } },
    { year: 50, cash: { lo: 34064807.5275, hi: 65735911.5001 }, enrolled: { lo: 3000, hi: 5077.5 }, prestige: { lo: 112.4834, hi: 187.4907 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.1219, hi: 0.1669 }, weeksInTheRed: { lo: 0, hi: 157.5 } },
  ],
  "Regional engine": [
    { year: 5, cash: { lo: 3407467.8082, hi: 6684381.1469 }, enrolled: { lo: 1515.75, hi: 7361.25 }, prestige: { lo: 37.8848, hi: 86.9835 }, rank: { lo: 29.25, hi: 68.75 }, netMargin: { lo: 0.199, hi: 0.8296 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 3395244.0659, hi: 24254095.0135 }, enrolled: { lo: 8220, hi: 17200 }, prestige: { lo: 53.8199, hi: 109.9578 }, rank: { lo: 11.25, hi: 52.5 }, netMargin: { lo: -0.0573, hi: 0.2056 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: 9286805.0592, hi: 44407590.9436 }, enrolled: { lo: 12240, hi: 37100 }, prestige: { lo: 78.6942, hi: 157.6893 }, rank: { lo: 1, hi: 7 }, netMargin: { lo: -0.0949, hi: 0.1024 }, weeksInTheRed: { lo: 11, hi: 246.25 } },
    { year: 35, cash: { lo: -26650486.1583, hi: 154054146.9626 }, enrolled: { lo: 13560, hi: 37900 }, prestige: { lo: 83.2395, hi: 180.7788 }, rank: { lo: 1, hi: 11 }, netMargin: { lo: -0.1028, hi: 0.1018 }, weeksInTheRed: { lo: 11, hi: 577.5 } },
    { year: 50, cash: { lo: 68696346.3832, hi: 257400708.6107 }, enrolled: { lo: 21780, hi: 41900 }, prestige: { lo: 109.3659, hi: 187.3053 }, rank: { lo: 1, hi: 5 }, netMargin: { lo: -0.131, hi: 0.0858 }, weeksInTheRed: { lo: 226.5, hi: 935 } },
  ],
  "Idle (builds nothing)": [
    { year: 5, cash: { lo: 5805841.3217, hi: 9686955.9407 }, enrolled: { lo: 337.5, hi: 565 }, prestige: { lo: 30.911, hi: 51.5426 }, rank: { lo: 45, hi: 80 }, netMargin: { lo: -0.003, hi: 0.0976 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 7113568.9294, hi: 11949469.5709 }, enrolled: { lo: 337.5, hi: 562.5 }, prestige: { lo: 30.976, hi: 51.6597 }, rank: { lo: 45.75, hi: 80 }, netMargin: { lo: -0.0102, hi: 0.0898 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: 10210025.8298, hi: 18447063.5313 }, enrolled: { lo: 338.25, hi: 563.75 }, prestige: { lo: 31.3857, hi: 52.3613 }, rank: { lo: 48.75, hi: 82.5 }, netMargin: { lo: -0.0122, hi: 0.0878 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 35, cash: { lo: 19774408.3413, hi: 34283416.6574 }, enrolled: { lo: 70, hi: 448 }, prestige: { lo: 17.0923, hi: 42.2167 }, rank: { lo: 58.5, hi: 112.5 }, netMargin: { lo: -0.0457, hi: 0.2554 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 50, cash: { lo: 27691224.86, hi: 60461849.7459 }, enrolled: { lo: 20, hi: 522.5 }, prestige: { lo: 17.2664, hi: 44.8512 }, rank: { lo: 57.75, hi: 113.75 }, netMargin: { lo: -0.1652, hi: 0.2531 }, weeksInTheRed: { lo: 0, hi: 10 } },
  ],
};
// --- END GENERATED ---
