// ---------------------------------------------------------------------
// The scorecard: each strategy's trajectory as numbers it can be held to
// (test/balance-scorecard.test.ts fails on either kind of band).
//
// TARGETS are hand-written: where the game should be, for the Balanced
// builder and the two controls. REFERENCE is generated by `npm run sim --
// --write-reference`: where every other strategy is, the envelope of three
// seeds at +/-TOLERANCE, so a change that moves a trajectory is noticed.
//
// Not part of the game: nothing in src/ imports this.
// ---------------------------------------------------------------------

import type { Row } from './balanceSim';

// The years a trajectory is read at, across the three eras: found (1-12),
// build (12-35), defend (35-50).
export const REFERENCE_YEARS = [5, 10, 20, 35, 50] as const;
export const REFERENCE_HORIZON = 50;

// The two extra streams `--write-reference` plays beside the default seed,
// so a band is the envelope of three runs rather than a claim about one.
export const REFERENCE_EXTRA_SEEDS = [4242, 777];

// How far either side of the recorded figure still counts as the same run.
// Wide on purpose: the economy is a threshold system, so small changes move
// which week something is built and decades compound it. One tolerance for
// every metric, which is looser on bounded prestige than on cash.
export const TOLERANCE = 0.25;

// A floor on each band's half-width, in the metric's own units, because a
// percentage of a number near zero is no band at all.
const FLOOR: Record<Metric, number> = {
  cash: 1_000_000,      // a million dollars is a rounding error by year 10
  enrolled: 100,        // a hundred students
  prestige: 2,          // two points on a 5..150 scale
  rank: 3,              // three places in a hundred-school field
  netMargin: 0.05,      // five points of margin
  weeksInTheRed: 10,    // ten weeks over the five years a sample covers
};

export type Metric = 'cash' | 'enrolled' | 'prestige' | 'rank' | 'netMargin' | 'weeksInTheRed';

export const METRICS: Metric[] = ['cash', 'enrolled', 'prestige', 'rank', 'netMargin', 'weeksInTheRed'];

export interface Band { lo: number; hi: number }
export type ReferenceRow = { year: number } & Record<Metric, Band>;
export type Reference = Record<string, ReferenceRow[]>;

// Net weekly margin as a share of weekly operating cost; 0 when opex is 0.
export function netMargin(row: Row): number {
  return row.opex > 0 ? row.net / row.opex : 0;
}

export function metricOf(row: Row, metric: Metric): number {
  switch (metric) {
    case 'cash': return row.cash;
    case 'enrolled': return row.enrolled;
    case 'prestige': return row.prestige;
    case 'rank': return row.rank;
    case 'netMargin': return netMargin(row);
    case 'weeksInTheRed': return row.weeksInTheRed;
  }
}

// A band around one figure. Written so a NEGATIVE value bands correctly:
// -14M ±25% is [-17.5M, -10.5M], not the inside-out range the naive
// arithmetic gives.
export function bandAround(value: number, metric: Metric): Band {
  const half = Math.max(Math.abs(value) * TOLERANCE, FLOOR[metric]);
  // Two of the five metrics cannot be negative, and a band whose floor is
  // "-10 weeks in the red" is noise in the file rather than a statement.
  const floorAtZero = metric === 'weeksInTheRed' || metric === 'enrolled';
  if (metric === 'rank') return { lo: Math.max(1, value - half), hi: value + half };
  return { lo: floorAtZero ? Math.max(0, value - half) : value - half, hi: value + half };
}

// The bands a run implies — what `--write-reference` commits.
export function bandsFrom(rows: Row[]): ReferenceRow[] {
  const out: ReferenceRow[] = [];
  for (const year of REFERENCE_YEARS) {
    const row = rows.find((r) => r.year === year);
    if (!row) continue;
    out.push({
      year,
      cash: bandAround(row.cash, 'cash'),
      enrolled: bandAround(row.enrolled, 'enrolled'),
      prestige: bandAround(row.prestige, 'prestige'),
      rank: bandAround(row.rank, 'rank'),
      netMargin: bandAround(netMargin(row), 'netMargin'),
      weeksInTheRed: bandAround(row.weeksInTheRed, 'weeksInTheRed'),
    });
  }
  return out;
}

// The envelope across several runs of one strategy: the lowest low and the
// highest high of the seeds' bands.
export function bandsAcross(runs: Row[][]): ReferenceRow[] {
  const perSeed = runs.map((rows) => bandsFrom(rows));
  const out: ReferenceRow[] = [];
  for (const year of REFERENCE_YEARS) {
    const rows = perSeed.map((bands) => bands.find((r) => r.year === year)).filter((r): r is ReferenceRow => r !== undefined);
    if (rows.length === 0) continue;
    const merged = { year } as ReferenceRow;
    for (const metric of METRICS) {
      merged[metric] = {
        lo: Math.min(...rows.map((r) => r[metric].lo)),
        hi: Math.max(...rows.map((r) => r[metric].hi)),
      };
    }
    out.push(merged);
  }
  return out;
}

// The bands a strategy is held to: a hand-written TARGET where one exists,
// the generated envelope otherwise (see TARGETS below).
export function bandsFor(strategyName: string): ReferenceRow[] | undefined {
  return TARGETS[strategyName] ?? REFERENCE[strategyName];
}

export interface Finding {
  strategy: string;
  year: number;
  metric: Metric;
  value: number;
  band: Band;
  side: 'HIGH' | 'LOW';
}

// Every figure outside its band. A year with no recorded band is skipped:
// an absent band is a missing statement, not a failing one.
export function findingsFor(strategyName: string, rows: Row[]): Finding[] {
  const reference = bandsFor(strategyName);
  if (!reference) return [];
  const findings: Finding[] = [];
  for (const expected of reference) {
    const row = rows.find((r) => r.year === expected.year);
    if (!row) continue;
    for (const metric of METRICS) {
      const value = metricOf(row, metric);
      const band = expected[metric];
      if (value < band.lo) findings.push({ strategy: strategyName, year: expected.year, metric, value, band, side: 'LOW' });
      else if (value > band.hi) findings.push({ strategy: strategyName, year: expected.year, metric, value, band, side: 'HIGH' });
    }
  }
  return findings;
}

function short(n: number, metric: Metric): string {
  if (metric === 'netMargin') return `${(n * 100).toFixed(0)}%`;
  if (metric === 'weeksInTheRed' || metric === 'rank') return n.toFixed(0);
  if (metric === 'prestige') return n.toFixed(1);
  const abs = Math.abs(n);
  const sign = n < 0 ? '-' : '';
  if (abs >= 1e9) return `${sign}${(abs / 1e9).toFixed(2)}B`;
  if (abs >= 1e6) return `${sign}${(abs / 1e6).toFixed(1)}M`;
  if (abs >= 1e3) return `${sign}${(abs / 1e3).toFixed(0)}k`;
  return `${sign}${abs.toFixed(0)}`;
}

// One line per finding, in the shape the plan asked for:
//   year 20 enrolled 42,000 (band 8,000–14,000) HIGH
export function describeFinding(f: Finding): string {
  return `year ${String(f.year).padStart(2)} ${f.metric.padEnd(13)} `
    + `${short(f.value, f.metric).padStart(8)} (band ${short(f.band.lo, f.metric)}–${short(f.band.hi, f.metric)}) ${f.side}`;
}

// The generated source of the block below, so `--write-reference` writes
// this file the way a human would have.
export function serialiseReference(reference: Reference): string {
  const round = (n: number) => Number(n.toFixed(4));
  const entries = Object.entries(reference).map(([name, rows]) => {
    const body = rows.map((row) => {
      const fields = METRICS
        .map((m) => `${m}: { lo: ${round(row[m].lo)}, hi: ${round(row[m].hi)} }`)
        .join(', ');
      return `    { year: ${row.year}, ${fields} },`;
    }).join('\n');
    return `  ${JSON.stringify(name)}: [\n${body}\n  ],`;
  }).join('\n');
  return `export const REFERENCE: Reference = {\n${entries}\n};`;
}

// =====================================================================
// TARGETS: where the game should be. Hand-written, never generated, and
// they take precedence over REFERENCE for the strategies they name.
// =====================================================================
//
// - Balanced builder: the design table in docs/plans/15-growth-has-a-cost.md
//   (section 6), re-read for a college that opens teaching, which puts it
//   about a decade ahead of those eras in standing: top fifty by year 5,
//   rank #1 by year 20. Enrolment bands are wide because seeds diverge on
//   when the catalogue is finished. Net margin is 25-40% while building and
//   5-15% from year 35, and positive at 50 because a mature builder keeps
//   building (balanceSim.ts's HEADROOM_OPEX_CAP). Cash is loose: "one to
//   three years of surplus" is a relation, not a figure.
// - Idle: a small college that never grows, ten points under its founding
//   standing within five years and held there, at its founding seats.
// - Overbuilder: underwater around year 5 (a coin flip on the seed, so the
//   year-5 row allows "within a million of it"; year 10 requires a red
//   week), then it stalls or keeps sinking depending on the seed. The cash
//   floors at years 20, 35 and 50 cover the sinking seeds;
//   test/balance-regression.test.ts holds the "stall, don't die" claims.
export const TARGETS: Reference = {
  'Balanced builder': [
    { year: 5, cash: { lo: -2_000_000, hi: 20_000_000 }, enrolled: { lo: 1_000, hi: 3_500 }, prestige: { lo: 45, hi: 75 }, rank: { lo: 30, hi: 70 }, netMargin: { lo: 0.1, hi: 0.6 }, weeksInTheRed: { lo: 0, hi: 60 } },
    { year: 10, cash: { lo: -2_000_000, hi: 40_000_000 }, enrolled: { lo: 4_000, hi: 16_000 }, prestige: { lo: 55, hi: 95 }, rank: { lo: 12, hi: 60 }, netMargin: { lo: 0.05, hi: 0.5 }, weeksInTheRed: { lo: 0, hi: 120 } },
    { year: 20, cash: { lo: -5_000_000, hi: 300_000_000 }, enrolled: { lo: 8_000, hi: 32_000 }, prestige: { lo: 80, hi: 140 }, rank: { lo: 1, hi: 20 }, netMargin: { lo: -0.05, hi: 0.4 }, weeksInTheRed: { lo: 0, hi: 200 } },
    { year: 35, cash: { lo: -20_000_000, hi: 2_000_000_000 }, enrolled: { lo: 12_000, hi: 40_000 }, prestige: { lo: 100, hi: 150 }, rank: { lo: 1, hi: 8 }, netMargin: { lo: -0.05, hi: 0.2 }, weeksInTheRed: { lo: 0, hi: 400 } },
    // Year 50's margin ceiling was 30% until Plan 29: retirement hands back
    // each long-serving professor's seniority premium, and the successor
    // starts at a junior salary, so a well-run college's late payroll
    // falls. Measured at 26%, 32% and 13% on the three seeds (8%, 14% and
    // 25% before). Plan 30's annual fund added alumni giving on top, and the
    // default seed read 42%: the ceiling is 45%. That is twice in two plans
    // the late margin has risen; Phase N owns it (V1-25).
    { year: 50, cash: { lo: -20_000_000, hi: 5_000_000_000 }, enrolled: { lo: 15_000, hi: 42_000 }, prestige: { lo: 110, hi: 150 }, rank: { lo: 1, hi: 5 }, netMargin: { lo: 0, hi: 0.45 }, weeksInTheRed: { lo: 0, hi: 500 } },
  ],
  'Idle (builds nothing)': [
    { year: 5, cash: { lo: 0, hi: 50_000_000 }, enrolled: { lo: 0, hi: 480 }, prestige: { lo: 5, hi: 45 }, rank: { lo: 60, hi: 100 }, netMargin: { lo: -1, hi: 3 }, weeksInTheRed: { lo: 0, hi: 100 } },
    { year: 10, cash: { lo: 0, hi: 50_000_000 }, enrolled: { lo: 0, hi: 480 }, prestige: { lo: 5, hi: 44 }, rank: { lo: 60, hi: 100 }, netMargin: { lo: -1, hi: 3 }, weeksInTheRed: { lo: 0, hi: 200 } },
    { year: 20, cash: { lo: 0, hi: 50_000_000 }, enrolled: { lo: 0, hi: 480 }, prestige: { lo: 5, hi: 44 }, rank: { lo: 60, hi: 100 }, netMargin: { lo: -1, hi: 3 }, weeksInTheRed: { lo: 0, hi: 500 } },
    { year: 35, cash: { lo: 0, hi: 50_000_000 }, enrolled: { lo: 0, hi: 480 }, prestige: { lo: 5, hi: 44 }, rank: { lo: 60, hi: 100 }, netMargin: { lo: -1, hi: 3 }, weeksInTheRed: { lo: 0, hi: 1_000 } },
    // Year 50's cash ceiling was $50M until Plan 30: even an idle college's
    // few hundred graduates give to the annual fund ($53M at the default seed).
    { year: 50, cash: { lo: 0, hi: 75_000_000 }, enrolled: { lo: 0, hi: 480 }, prestige: { lo: 5, hi: 44 }, rank: { lo: 60, hi: 100 }, netMargin: { lo: -1, hi: 3 }, weeksInTheRed: { lo: 0, hi: 1_500 } },
  ],
  'Overbuilder (beds ahead of demand)': [
    { year: 5, cash: { lo: -6_000_000, hi: 1_000_000 }, enrolled: { lo: 300, hi: 2_000 }, prestige: { lo: 30, hi: 65 }, rank: { lo: 40, hi: 90 }, netMargin: { lo: -0.5, hi: 0.15 }, weeksInTheRed: { lo: 0, hi: 260 } },
    { year: 10, cash: { lo: -8_000_000, hi: 3_000_000 }, enrolled: { lo: 300, hi: 3_000 }, prestige: { lo: 30, hi: 70 }, rank: { lo: 35, hi: 90 }, netMargin: { lo: -0.5, hi: 0.2 }, weeksInTheRed: { lo: 1, hi: 520 } },
    { year: 20, cash: { lo: -30_000_000, hi: 10_000_000 }, enrolled: { lo: 300, hi: 5_000 }, prestige: { lo: 30, hi: 75 }, rank: { lo: 30, hi: 90 }, netMargin: { lo: -0.4, hi: 0.3 }, weeksInTheRed: { lo: 1, hi: 1_040 } },
    // Years 35 and 50's prestige and margin floors were 30 and -40% until
    // Plan 29: the faculty it hired early retire from year 25 on, into a
    // college in receivership that is also cutting its payroll, and it stalls
    // lower: at 4242 it bottoms out in year 35 at 297 students and prestige
    // 24, and recovers to 407 and 27 by year 50.
    // Plan 31 made building condition a prestige input, and a college in
    // austerity has had its maintenance cut by the board: its buildings run
    // down and its name follows. Year 35's rank ceiling was 90 and year 50's
    // prestige floor 25: at 4242 it reads rank 93 at year 35, and at 777
    // prestige 24 at year 50 (27.6 and 32.1 without the penalty).
    { year: 35, cash: { lo: -40_000_000, hi: 30_000_000 }, enrolled: { lo: 250, hi: 8_000 }, prestige: { lo: 20, hi: 80 }, rank: { lo: 25, hi: 95 }, netMargin: { lo: -0.6, hi: 0.4 }, weeksInTheRed: { lo: 1, hi: 1_820 } },
    { year: 50, cash: { lo: -50_000_000, hi: 60_000_000 }, enrolled: { lo: 300, hi: 10_000 }, prestige: { lo: 20, hi: 85 }, rank: { lo: 20, hi: 90 }, netMargin: { lo: -0.6, hi: 0.5 }, weeksInTheRed: { lo: 1, hi: 2_600 } },
  ],
};

// `--write-reference` rewrites between the markers below. The marker text
// lives in balanceSim.ts as string literals, not as exported constants here:
// a constant declaring a marker would itself match, and the writer would
// overwrite its own declaration.

// --- GENERATED by `npm run sim -- --write-reference`. Do not hand-edit lightly. ---
export const REFERENCE: Reference = {
  "Balanced builder": [
    { year: 5, cash: { lo: 2565637.4304, hi: 4782745.8777 }, enrolled: { lo: 1200, hi: 2300 }, prestige: { lo: 49.9792, hi: 84.6551 }, rank: { lo: 30.75, hi: 62.5 }, netMargin: { lo: 0.1514, hi: 0.2745 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 5403400.4353, hi: 26280591.3925 }, enrolled: { lo: 5940, hi: 12793.75 }, prestige: { lo: 53.7044, hi: 93.0396 }, rank: { lo: 24, hi: 46.25 }, netMargin: { lo: 0.1786, hi: 0.3806 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: 8341792.4481, hi: 19323798.857 }, enrolled: { lo: 17400, hi: 34800 }, prestige: { lo: 98.5324, hi: 168.0902 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.0221, hi: 0.1234 }, weeksInTheRed: { lo: 0, hi: 125 } },
    { year: 35, cash: { lo: 91236933.3267, hi: 342206437.1699 }, enrolled: { lo: 25080, hi: 42200 }, prestige: { lo: 111.5331, hi: 186.9377 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: 0.0359, hi: 0.1425 }, weeksInTheRed: { lo: 0, hi: 125 } },
    { year: 50, cash: { lo: 219355994.3344, hi: 391138677.2116 }, enrolled: { lo: 25140, hi: 42700 }, prestige: { lo: 112.472, hi: 187.4837 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: 0.2306, hi: 0.5289 }, weeksInTheRed: { lo: 0, hi: 125 } },
  ],
  "Curriculum rush (overreach)": [
    { year: 5, cash: { lo: -106399.7488, hi: 4255189.9796 }, enrolled: { lo: 505.5, hi: 1090 }, prestige: { lo: 29.8085, hi: 54.7329 }, rank: { lo: 45.75, hi: 81.25 }, netMargin: { lo: -0.1216, hi: 0.1699 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: -3184803.9111, hi: 2231861.2053 }, enrolled: { lo: 440.25, hi: 1288.75 }, prestige: { lo: 30.7757, hi: 59.7352 }, rank: { lo: 42.75, hi: 82.5 }, netMargin: { lo: -0.0273, hi: 0.1811 }, weeksInTheRed: { lo: 0, hi: 231.25 } },
    { year: 20, cash: { lo: -13689228.6109, hi: 1295608.2948 }, enrolled: { lo: 325.5, hi: 1945 }, prestige: { lo: 28.1474, hi: 63.592 }, rank: { lo: 42, hi: 92.5 }, netMargin: { lo: -0.2685, hi: 0.3844 }, weeksInTheRed: { lo: 0, hi: 881.25 } },
    { year: 35, cash: { lo: -44291422.311, hi: 18380400.9689 }, enrolled: { lo: 205, hi: 40300 }, prestige: { lo: 22.6142, hi: 142.7711 }, rank: { lo: 1, hi: 98.75 }, netMargin: { lo: -0.2471, hi: 0.4773 }, weeksInTheRed: { lo: 0, hi: 1856.25 } },
    { year: 50, cash: { lo: -67743941.6857, hi: 6539420014.4063 }, enrolled: { lo: 193, hi: 42700 }, prestige: { lo: 23.623, hi: 186.2051 }, rank: { lo: 1, hi: 105 }, netMargin: { lo: -0.2343, hi: 0.1525 }, weeksInTheRed: { lo: 0, hi: 2831.25 } },
  ],
  "Discount volume (beds first)": [
    { year: 5, cash: { lo: -1628000.7907, hi: 764620.1466 }, enrolled: { lo: 420, hi: 700 }, prestige: { lo: 50.7731, hi: 84.6489 }, rank: { lo: 32.25, hi: 60 }, netMargin: { lo: -0.1426, hi: -0.0257 }, weeksInTheRed: { lo: 0, hi: 31 } },
    { year: 10, cash: { lo: -4045902.2756, hi: -867510.0599 }, enrolled: { lo: 420, hi: 700 }, prestige: { lo: 56.374, hi: 94.1867 }, rank: { lo: 20.25, hi: 40 }, netMargin: { lo: -0.0355, hi: 0.0921 }, weeksInTheRed: { lo: 201, hi: 351.25 } },
    { year: 20, cash: { lo: -1136628.6783, hi: 2818835.5108 }, enrolled: { lo: 420, hi: 700 }, prestige: { lo: 56.7883, hi: 95.374 }, rank: { lo: 21, hi: 43.75 }, netMargin: { lo: -0.1107, hi: 0.1027 }, weeksInTheRed: { lo: 376.5, hi: 838.75 } },
    { year: 35, cash: { lo: 5009071.1152, hi: 10601069.3464 }, enrolled: { lo: 2100, hi: 6800 }, prestige: { lo: 44.4399, hi: 82.7602 }, rank: { lo: 32.25, hi: 66.25 }, netMargin: { lo: 0.059, hi: 0.4886 }, weeksInTheRed: { lo: 383.25, hi: 1045 } },
    { year: 50, cash: { lo: 2411221.1565, hi: 13172333.0597 }, enrolled: { lo: 4080, hi: 10900 }, prestige: { lo: 63.0677, hi: 120.1999 }, rank: { lo: 12, hi: 38.75 }, netMargin: { lo: -0.0588, hi: 0.166 }, weeksInTheRed: { lo: 543, hi: 1207.5 } },
  ],
  "Completionist (build everything)": [
    { year: 5, cash: { lo: -145068.0388, hi: 3845127.7503 }, enrolled: { lo: 480, hi: 1400 }, prestige: { lo: 50.8899, hi: 86.2477 }, rank: { lo: 31.5, hi: 58.75 }, netMargin: { lo: -0.0671, hi: 0.1727 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: -646843.1835, hi: 6335523.8764 }, enrolled: { lo: 480, hi: 5600 }, prestige: { lo: 55.9956, hi: 103.159 }, rank: { lo: 14.25, hi: 42.5 }, netMargin: { lo: 0.0242, hi: 0.3435 }, weeksInTheRed: { lo: 0, hi: 127.5 } },
    { year: 20, cash: { lo: 622407.854, hi: 15429448.7928 }, enrolled: { lo: 480, hi: 35300 }, prestige: { lo: 65.5116, hi: 164.4253 }, rank: { lo: 1, hi: 27.5 }, netMargin: { lo: -0.0128, hi: 0.096 }, weeksInTheRed: { lo: 33, hi: 127.5 } },
    { year: 35, cash: { lo: 7452237.7464, hi: 254123838.5469 }, enrolled: { lo: 5580, hi: 42700 }, prestige: { lo: 63.9768, hi: 186.832 }, rank: { lo: 1, hi: 41.25 }, netMargin: { lo: 0.1261, hi: 0.2726 }, weeksInTheRed: { lo: 33, hi: 127.5 } },
    { year: 50, cash: { lo: 55342714.2478, hi: 405939790.7015 }, enrolled: { lo: 22140, hi: 42700 }, prestige: { lo: 108.0319, hi: 187.4807 }, rank: { lo: 1, hi: 5 }, netMargin: { lo: -0.015, hi: 0.9962 }, weeksInTheRed: { lo: 33, hi: 135 } },
  ],
  "Overbuilder (beds ahead of demand)": [
    { year: 5, cash: { lo: -1250484.7067, hi: 1398634.4829 }, enrolled: { lo: 634.5, hi: 1293.75 }, prestige: { lo: 24.8008, hi: 50.8123 }, rank: { lo: 45, hi: 91.25 }, netMargin: { lo: -0.264, hi: -0.0254 }, weeksInTheRed: { lo: 0, hi: 35 } },
    { year: 10, cash: { lo: -8520475.3957, hi: 828215.0101 }, enrolled: { lo: 321, hi: 1086.25 }, prestige: { lo: 19.1504, hi: 46.5789 }, rank: { lo: 51.75, hi: 107.5 }, netMargin: { lo: -0.3946, hi: 0.0279 }, weeksInTheRed: { lo: 182.25, hi: 356.25 } },
    { year: 20, cash: { lo: -31942509.836, hi: -4462110.4328 }, enrolled: { lo: 152, hi: 872.5 }, prestige: { lo: 16.1911, hi: 44.848 }, rank: { lo: 54.75, hi: 112.5 }, netMargin: { lo: -0.6294, hi: -0.0421 }, weeksInTheRed: { lo: 572.25, hi: 1006.25 } },
    { year: 35, cash: { lo: -69814561.5181, hi: -9224322.3601 }, enrolled: { lo: 85, hi: 386 }, prestige: { lo: 11.3008, hi: 28.2761 }, rank: { lo: 66.75, hi: 116.25 }, netMargin: { lo: -0.441, hi: -0.0427 }, weeksInTheRed: { lo: 1157.25, hi: 1981.25 } },
    { year: 50, cash: { lo: -95989463.1459, hi: -16342150.14 }, enrolled: { lo: 113, hi: 497 }, prestige: { lo: 14.6657, hi: 31.617 }, rank: { lo: 66.75, hi: 113.75 }, netMargin: { lo: -0.5422, hi: -0.0813 }, weeksInTheRed: { lo: 1742.25, hi: 2956.25 } },
  ],
  "Earnest completionist": [
    { year: 5, cash: { lo: 928787.843, hi: 3451623.0794 }, enrolled: { lo: 1740, hi: 3200 }, prestige: { lo: 48.4639, hi: 81.4281 }, rank: { lo: 36, hi: 63.75 }, netMargin: { lo: 0.304, hi: 0.5331 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 12252557.4558, hi: 33951984.6888 }, enrolled: { lo: 12480, hi: 21100 }, prestige: { lo: 56.852, hi: 104.1329 }, rank: { lo: 12.75, hi: 37.5 }, netMargin: { lo: 0.1533, hi: 0.3813 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: 47978128.1541, hi: 102008198.1471 }, enrolled: { lo: 20580, hi: 37800 }, prestige: { lo: 105.6315, hi: 177.8835 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.0049, hi: 0.1438 }, weeksInTheRed: { lo: 0, hi: 183.75 } },
    { year: 35, cash: { lo: 187484288.8656, hi: 397424680.4978 }, enrolled: { lo: 25140, hi: 42300 }, prestige: { lo: 112.3012, hi: 187.2216 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: 0.1246, hi: 0.3601 }, weeksInTheRed: { lo: 0, hi: 183.75 } },
    { year: 50, cash: { lo: 225876897.817, hi: 458454839.823 }, enrolled: { lo: 25140, hi: 42300 }, prestige: { lo: 112.4942, hi: 187.4919 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: 0.5258, hi: 1.2848 }, weeksInTheRed: { lo: 0, hi: 183.75 } },
  ],
  "Scatterer (founds anything anywhere)": [
    { year: 5, cash: { lo: 3270365.157, hi: 6266773.7214 }, enrolled: { lo: 1754.25, hi: 3000 }, prestige: { lo: 46.0215, hi: 82.864 }, rank: { lo: 31.5, hi: 66.25 }, netMargin: { lo: 0.2036, hi: 0.5073 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 5904702.0482, hi: 17103882.7922 }, enrolled: { lo: 7056, hi: 15326.25 }, prestige: { lo: 52.7044, hi: 98.1576 }, rank: { lo: 18.75, hi: 51.25 }, netMargin: { lo: 0.1335, hi: 0.3783 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: 31581921.3023, hi: 196670248.2907 }, enrolled: { lo: 20580, hi: 34300 }, prestige: { lo: 76.1843, hi: 136.1097 }, rank: { lo: 1, hi: 11 }, netMargin: { lo: 0.0233, hi: 0.1341 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 35, cash: { lo: 133399085.3946, hi: 230451786.1951 }, enrolled: { lo: 20580, hi: 34300 }, prestige: { lo: 81.7607, hi: 148.5199 }, rank: { lo: 1, hi: 9 }, netMargin: { lo: 0.1565, hi: 0.3842 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 50, cash: { lo: 130462362.9844, hi: 247855858.9094 }, enrolled: { lo: 20580, hi: 34300 }, prestige: { lo: 83.9944, hi: 152.7803 }, rank: { lo: 1, hi: 11 }, netMargin: { lo: 0.3767, hi: 0.9203 }, weeksInTheRed: { lo: 0, hi: 10 } },
  ],
  "Selective college": [
    { year: 5, cash: { lo: 1662467.5176, hi: 4447542.1138 }, enrolled: { lo: 737.25, hi: 1682.5 }, prestige: { lo: 50.5721, hi: 96.7943 }, rank: { lo: 20.25, hi: 60 }, netMargin: { lo: 0.4353, hi: 0.9054 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 4231677.7457, hi: 22856609.507 }, enrolled: { lo: 3003.75, hi: 6762.5 }, prestige: { lo: 61.3258, hi: 118.0257 }, rank: { lo: 2, hi: 22.5 }, netMargin: { lo: 0.293, hi: 0.6455 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: 31943299.2535, hi: 57906793.2634 }, enrolled: { lo: 3054.75, hi: 5186.25 }, prestige: { lo: 106.6199, hi: 180.104 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.0973, hi: 0.0524 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 35, cash: { lo: 23428409.6775, hi: 64199098.4333 }, enrolled: { lo: 3003, hi: 5026.25 }, prestige: { lo: 112.3298, hi: 187.2859 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: 0.1677, hi: 0.6443 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 50, cash: { lo: 32638937.4429, hi: 58895565.8394 }, enrolled: { lo: 2987.25, hi: 5022.5 }, prestige: { lo: 112.4951, hi: 187.4938 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: 0.5836, hi: 1.5264 }, weeksInTheRed: { lo: 0, hi: 10 } },
  ],
  "Regional engine": [
    { year: 5, cash: { lo: 710719.4848, hi: 5239497.8953 }, enrolled: { lo: 1440, hi: 3000 }, prestige: { lo: 47.6841, hi: 83.9724 }, rank: { lo: 32.25, hi: 62.5 }, netMargin: { lo: 0.2344, hi: 0.4977 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 11462729.8299, hi: 22676282.6125 }, enrolled: { lo: 11100, hi: 19300 }, prestige: { lo: 57.3418, hi: 111.5327 }, rank: { lo: 8, hi: 42.5 }, netMargin: { lo: 0.0041, hi: 0.3209 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: 17791266.8386, hi: 55887850.0829 }, enrolled: { lo: 14700, hi: 31200 }, prestige: { lo: 95.6978, hi: 175.6625 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.0354, hi: 0.1042 }, weeksInTheRed: { lo: 0, hi: 130 } },
    { year: 35, cash: { lo: 67930279.4455, hi: 320390708.3496 }, enrolled: { lo: 24120, hi: 41800 }, prestige: { lo: 111.7494, hi: 187.0652 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.0002, hi: 0.1261 }, weeksInTheRed: { lo: 0, hi: 130 } },
    { year: 50, cash: { lo: 164954962.5457, hi: 386150241.9905 }, enrolled: { lo: 25140, hi: 42300 }, prestige: { lo: 112.4783, hi: 187.4874 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: 0.064, hi: 0.1785 }, weeksInTheRed: { lo: 0, hi: 130 } },
  ],
  "Idle (builds nothing)": [
    { year: 5, cash: { lo: 4500424.1238, hi: 7978931.9305 }, enrolled: { lo: 340.5, hi: 567.5 }, prestige: { lo: 30.9224, hi: 51.5518 }, rank: { lo: 45.75, hi: 81.25 }, netMargin: { lo: 0.032, hi: 0.1401 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 5870580.8321, hi: 9964511.1021 }, enrolled: { lo: 336.75, hi: 561.25 }, prestige: { lo: 31.0342, hi: 51.7642 }, rank: { lo: 47.25, hi: 82.5 }, netMargin: { lo: 0.0468, hi: 0.1555 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: 9846181.714, hi: 16453262.7237 }, enrolled: { lo: 338.25, hi: 563.75 }, prestige: { lo: 31.5332, hi: 52.5661 }, rank: { lo: 50.25, hi: 86.25 }, netMargin: { lo: 0.1076, hi: 0.2086 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 35, cash: { lo: 21158952.0536, hi: 35838614.1516 }, enrolled: { lo: 292, hi: 532.5 }, prestige: { lo: 26.2527, hi: 45.7191 }, rank: { lo: 54.75, hi: 101.25 }, netMargin: { lo: 0.3011, hi: 0.613 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 50, cash: { lo: 38741262.4241, hi: 66556128.242 }, enrolled: { lo: 338.25, hi: 565 }, prestige: { lo: 30.3648, hi: 53.6942 }, rank: { lo: 54, hi: 96.25 }, netMargin: { lo: 0.3295, hi: 0.5927 }, weeksInTheRed: { lo: 0, hi: 10 } },
  ],
};
// --- END GENERATED ---
