// ---------------------------------------------------------------------
// The scorecard: each strategy's trajectory as numbers it can be held to
// (test/balance-scorecard.test.ts fails on either kind of band).
//
// TARGETS are hand-written: where the game should be, for the Balanced
// builder and the two controls. REFERENCE is generated by `npm run sim --
// --write-reference`: where every other strategy is, the envelope of three
// seeds at +/-TOLERANCE, so a change that moves a trajectory is noticed.
//
// Not part of the game: nothing in src/ imports this.
// ---------------------------------------------------------------------

import type { Row } from './balanceSim';

// The years a trajectory is read at, across the three eras: found (1-12),
// build (12-35), defend (35-50).
export const REFERENCE_YEARS = [5, 10, 20, 35, 50] as const;
export const REFERENCE_HORIZON = 50;

// The two extra streams `--write-reference` plays beside the default seed,
// so a band is the envelope of three runs rather than a claim about one.
export const REFERENCE_EXTRA_SEEDS = [4242, 777];

// How far either side of the recorded figure still counts as the same run.
// Wide on purpose: the economy is a threshold system, so small changes move
// which week something is built and decades compound it. One tolerance for
// every metric, which is looser on bounded prestige than on cash.
export const TOLERANCE = 0.25;

// A floor on each band's half-width, in the metric's own units, because a
// percentage of a number near zero is no band at all.
const FLOOR: Record<Metric, number> = {
  cash: 1_000_000,      // a million dollars is a rounding error by year 10
  enrolled: 100,        // a hundred students
  prestige: 2,          // two points on a 5..150 scale
  rank: 3,              // three places in a hundred-school field
  netMargin: 0.05,      // five points of margin
  weeksInTheRed: 10,    // ten weeks over the five years a sample covers
};

export type Metric = 'cash' | 'enrolled' | 'prestige' | 'rank' | 'netMargin' | 'weeksInTheRed';

export const METRICS: Metric[] = ['cash', 'enrolled', 'prestige', 'rank', 'netMargin', 'weeksInTheRed'];

export interface Band { lo: number; hi: number }
export type ReferenceRow = { year: number } & Record<Metric, Band>;
export type Reference = Record<string, ReferenceRow[]>;

// The operating margin: the week's net less the endowment payout and the
// annual fund, as a share of weekly operating cost; 0 when opex is 0. The
// metric kept its name when Plan 35 took the endowment out of it (V1-25):
// the headline margin rose to 70% late in a run because the harness moves
// every spare dollar into the endowment, whose payout comes back as income.
// A rows file from before Plan 35 has no payout or fund, and reads as the
// headline margin.
export function netMargin(row: Row): number {
  return row.opex > 0 ? (row.net - (row.payout ?? 0) - (row.fund ?? 0)) / row.opex : 0;
}

export function metricOf(row: Row, metric: Metric): number {
  switch (metric) {
    case 'cash': return row.cash;
    case 'enrolled': return row.enrolled;
    case 'prestige': return row.prestige;
    case 'rank': return row.rank;
    case 'netMargin': return netMargin(row);
    case 'weeksInTheRed': return row.weeksInTheRed;
  }
}

// A band around one figure. Written so a NEGATIVE value bands correctly:
// -14M ±25% is [-17.5M, -10.5M], not the inside-out range the naive
// arithmetic gives.
export function bandAround(value: number, metric: Metric): Band {
  const half = Math.max(Math.abs(value) * TOLERANCE, FLOOR[metric]);
  // Two of the five metrics cannot be negative, and a band whose floor is
  // "-10 weeks in the red" is noise in the file rather than a statement.
  const floorAtZero = metric === 'weeksInTheRed' || metric === 'enrolled';
  if (metric === 'rank') return { lo: Math.max(1, value - half), hi: value + half };
  return { lo: floorAtZero ? Math.max(0, value - half) : value - half, hi: value + half };
}

// The bands a run implies — what `--write-reference` commits.
export function bandsFrom(rows: Row[]): ReferenceRow[] {
  const out: ReferenceRow[] = [];
  for (const year of REFERENCE_YEARS) {
    const row = rows.find((r) => r.year === year);
    if (!row) continue;
    out.push({
      year,
      cash: bandAround(row.cash, 'cash'),
      enrolled: bandAround(row.enrolled, 'enrolled'),
      prestige: bandAround(row.prestige, 'prestige'),
      rank: bandAround(row.rank, 'rank'),
      netMargin: bandAround(netMargin(row), 'netMargin'),
      weeksInTheRed: bandAround(row.weeksInTheRed, 'weeksInTheRed'),
    });
  }
  return out;
}

// The envelope across several runs of one strategy: the lowest low and the
// highest high of the seeds' bands.
export function bandsAcross(runs: Row[][]): ReferenceRow[] {
  const perSeed = runs.map((rows) => bandsFrom(rows));
  const out: ReferenceRow[] = [];
  for (const year of REFERENCE_YEARS) {
    const rows = perSeed.map((bands) => bands.find((r) => r.year === year)).filter((r): r is ReferenceRow => r !== undefined);
    if (rows.length === 0) continue;
    const merged = { year } as ReferenceRow;
    for (const metric of METRICS) {
      merged[metric] = {
        lo: Math.min(...rows.map((r) => r[metric].lo)),
        hi: Math.max(...rows.map((r) => r[metric].hi)),
      };
    }
    out.push(merged);
  }
  return out;
}

// The bands a strategy is held to: a hand-written TARGET where one exists,
// the generated envelope otherwise (see TARGETS below).
export function bandsFor(strategyName: string): ReferenceRow[] | undefined {
  return TARGETS[strategyName] ?? REFERENCE[strategyName];
}

export interface Finding {
  strategy: string;
  year: number;
  metric: Metric;
  value: number;
  band: Band;
  side: 'HIGH' | 'LOW';
}

// Every figure outside its band. A year with no recorded band is skipped:
// an absent band is a missing statement, not a failing one.
export function findingsFor(strategyName: string, rows: Row[]): Finding[] {
  const reference = bandsFor(strategyName);
  if (!reference) return [];
  const findings: Finding[] = [];
  for (const expected of reference) {
    const row = rows.find((r) => r.year === expected.year);
    if (!row) continue;
    for (const metric of METRICS) {
      const value = metricOf(row, metric);
      const band = expected[metric];
      if (value < band.lo) findings.push({ strategy: strategyName, year: expected.year, metric, value, band, side: 'LOW' });
      else if (value > band.hi) findings.push({ strategy: strategyName, year: expected.year, metric, value, band, side: 'HIGH' });
    }
  }
  return findings;
}

function short(n: number, metric: Metric): string {
  if (metric === 'netMargin') return `${(n * 100).toFixed(0)}%`;
  if (metric === 'weeksInTheRed' || metric === 'rank') return n.toFixed(0);
  if (metric === 'prestige') return n.toFixed(1);
  const abs = Math.abs(n);
  const sign = n < 0 ? '-' : '';
  if (abs >= 1e9) return `${sign}${(abs / 1e9).toFixed(2)}B`;
  if (abs >= 1e6) return `${sign}${(abs / 1e6).toFixed(1)}M`;
  if (abs >= 1e3) return `${sign}${(abs / 1e3).toFixed(0)}k`;
  return `${sign}${abs.toFixed(0)}`;
}

// One line per finding, in the shape the plan asked for:
//   year 20 enrolled 42,000 (band 8,000–14,000) HIGH
export function describeFinding(f: Finding): string {
  return `year ${String(f.year).padStart(2)} ${f.metric.padEnd(13)} `
    + `${short(f.value, f.metric).padStart(8)} (band ${short(f.band.lo, f.metric)}–${short(f.band.hi, f.metric)}) ${f.side}`;
}

// The generated source of the block below, so `--write-reference` writes
// this file the way a human would have.
export function serialiseReference(reference: Reference): string {
  const round = (n: number) => Number(n.toFixed(4));
  const entries = Object.entries(reference).map(([name, rows]) => {
    const body = rows.map((row) => {
      const fields = METRICS
        .map((m) => `${m}: { lo: ${round(row[m].lo)}, hi: ${round(row[m].hi)} }`)
        .join(', ');
      return `    { year: ${row.year}, ${fields} },`;
    }).join('\n');
    return `  ${JSON.stringify(name)}: [\n${body}\n  ],`;
  }).join('\n');
  return `export const REFERENCE: Reference = {\n${entries}\n};`;
}

// =====================================================================
// TARGETS: where the game should be. Hand-written, never generated, and
// they take precedence over REFERENCE for the strategies they name.
// =====================================================================
//
// - Balanced builder: the design table in docs/plans/15-growth-has-a-cost.md
//   (section 6), re-read for a college that opens teaching, which puts it
//   about a decade ahead of those eras in standing: top fifty by year 5,
//   rank #1 by year 20. Enrolment bands are wide because seeds diverge on
//   when the catalogue is finished. Net margin is 25-40% while building and
//   5-15% from year 35, and positive at 50 because a mature builder keeps
//   building (balanceSim.ts's HEADROOM_OPEX_CAP). Cash is loose: "one to
//   three years of surplus" is a relation, not a figure.
// - Idle: a small college that never grows, ten points under its founding
//   standing within five years and held there, at its founding seats.
// - Overbuilder: underwater around year 5 (a coin flip on the seed, so the
//   year-5 row allows "within a million of it"; year 10 requires a red
//   week), then it stalls or keeps sinking depending on the seed. The cash
//   floors at years 20, 35 and 50 cover the sinking seeds;
//   test/balance-regression.test.ts holds the "stall, don't die" claims.
export const TARGETS: Reference = {
  'Balanced builder': [
    { year: 5, cash: { lo: -2_000_000, hi: 20_000_000 }, enrolled: { lo: 1_000, hi: 3_500 }, prestige: { lo: 45, hi: 75 }, rank: { lo: 30, hi: 70 }, netMargin: { lo: 0.1, hi: 0.6 }, weeksInTheRed: { lo: 0, hi: 60 } },
    { year: 10, cash: { lo: -2_000_000, hi: 40_000_000 }, enrolled: { lo: 4_000, hi: 16_000 }, prestige: { lo: 55, hi: 95 }, rank: { lo: 12, hi: 60 }, netMargin: { lo: 0.05, hi: 0.5 }, weeksInTheRed: { lo: 0, hi: 120 } },
    { year: 20, cash: { lo: -5_000_000, hi: 300_000_000 }, enrolled: { lo: 8_000, hi: 32_000 }, prestige: { lo: 80, hi: 140 }, rank: { lo: 1, hi: 20 }, netMargin: { lo: -0.05, hi: 0.4 }, weeksInTheRed: { lo: 0, hi: 200 } },
    { year: 35, cash: { lo: -20_000_000, hi: 2_000_000_000 }, enrolled: { lo: 12_000, hi: 40_000 }, prestige: { lo: 100, hi: 150 }, rank: { lo: 1, hi: 8 }, netMargin: { lo: -0.05, hi: 0.2 }, weeksInTheRed: { lo: 0, hi: 400 } },
    // Year 50's margin was read with the endowment's payout in it until
    // Plan 35, and its ceiling had risen to 75% (Plans 29, 30 and 32). The
    // operating margin (netMargin above) is 1–3% from Year 15 on, and the
    // band is the mature college's.
    { year: 50, cash: { lo: -20_000_000, hi: 5_000_000_000 }, enrolled: { lo: 15_000, hi: 42_000 }, prestige: { lo: 110, hi: 150 }, rank: { lo: 1, hi: 5 }, netMargin: { lo: -0.05, hi: 0.2 }, weeksInTheRed: { lo: 0, hi: 500 } },
  ],
  'Idle (builds nothing)': [
    { year: 5, cash: { lo: 0, hi: 50_000_000 }, enrolled: { lo: 0, hi: 480 }, prestige: { lo: 5, hi: 45 }, rank: { lo: 60, hi: 100 }, netMargin: { lo: -1, hi: 3 }, weeksInTheRed: { lo: 0, hi: 100 } },
    { year: 10, cash: { lo: 0, hi: 50_000_000 }, enrolled: { lo: 0, hi: 480 }, prestige: { lo: 5, hi: 44 }, rank: { lo: 60, hi: 100 }, netMargin: { lo: -1, hi: 3 }, weeksInTheRed: { lo: 0, hi: 200 } },
    { year: 20, cash: { lo: 0, hi: 50_000_000 }, enrolled: { lo: 0, hi: 480 }, prestige: { lo: 5, hi: 44 }, rank: { lo: 60, hi: 100 }, netMargin: { lo: -1, hi: 3 }, weeksInTheRed: { lo: 0, hi: 500 } },
    { year: 35, cash: { lo: 0, hi: 50_000_000 }, enrolled: { lo: 0, hi: 480 }, prestige: { lo: 5, hi: 44 }, rank: { lo: 60, hi: 100 }, netMargin: { lo: -1, hi: 3 }, weeksInTheRed: { lo: 0, hi: 1_000 } },
    // Year 50's cash ceiling was $50M until Plan 30: even an idle college's
    // few hundred graduates give to the annual fund ($53M at the default seed).
    { year: 50, cash: { lo: 0, hi: 75_000_000 }, enrolled: { lo: 0, hi: 480 }, prestige: { lo: 5, hi: 44 }, rank: { lo: 60, hi: 100 }, netMargin: { lo: -1, hi: 3 }, weeksInTheRed: { lo: 0, hi: 1_500 } },
  ],
  'Overbuilder (beds ahead of demand)': [
    { year: 5, cash: { lo: -6_000_000, hi: 1_000_000 }, enrolled: { lo: 300, hi: 2_000 }, prestige: { lo: 30, hi: 65 }, rank: { lo: 40, hi: 90 }, netMargin: { lo: -0.5, hi: 0.15 }, weeksInTheRed: { lo: 0, hi: 260 } },
    { year: 10, cash: { lo: -8_000_000, hi: 3_000_000 }, enrolled: { lo: 300, hi: 3_000 }, prestige: { lo: 30, hi: 70 }, rank: { lo: 35, hi: 90 }, netMargin: { lo: -0.5, hi: 0.2 }, weeksInTheRed: { lo: 1, hi: 520 } },
    { year: 20, cash: { lo: -30_000_000, hi: 10_000_000 }, enrolled: { lo: 300, hi: 5_000 }, prestige: { lo: 30, hi: 75 }, rank: { lo: 30, hi: 90 }, netMargin: { lo: -0.4, hi: 0.3 }, weeksInTheRed: { lo: 1, hi: 1_040 } },
    // Years 35 and 50's prestige and margin floors were 30 and -40% until
    // Plan 29: the faculty it hired early retire from year 25 on, into a
    // college in receivership that is also cutting its payroll, and it stalls
    // lower: at 4242 it bottoms out in year 35 at 297 students and prestige
    // 24, and recovers to 407 and 27 by year 50.
    // Plan 31 made building condition a prestige input, and a college in
    // austerity has had its maintenance cut by the board: its buildings run
    // down and its name follows. Year 35's rank ceiling was 90 and year 50's
    // prestige floor 25: at 4242 it reads rank 93 at year 35, and at 777
    // prestige 24 at year 50 (27.6 and 32.1 without the penalty).
    { year: 35, cash: { lo: -40_000_000, hi: 30_000_000 }, enrolled: { lo: 250, hi: 8_000 }, prestige: { lo: 20, hi: 80 }, rank: { lo: 25, hi: 95 }, netMargin: { lo: -0.6, hi: 0.4 }, weeksInTheRed: { lo: 1, hi: 1_820 } },
    { year: 50, cash: { lo: -50_000_000, hi: 60_000_000 }, enrolled: { lo: 300, hi: 10_000 }, prestige: { lo: 20, hi: 85 }, rank: { lo: 20, hi: 90 }, netMargin: { lo: -0.6, hi: 0.5 }, weeksInTheRed: { lo: 1, hi: 2_600 } },
  ],
};

// `--write-reference` rewrites between the markers below. The marker text
// lives in balanceSim.ts as string literals, not as exported constants here:
// a constant declaring a marker would itself match, and the writer would
// overwrite its own declaration.

// --- GENERATED by `npm run sim -- --write-reference`. Do not hand-edit lightly. ---
export const REFERENCE: Reference = {
  "Balanced builder": [
    { year: 5, cash: { lo: 2885067.1218, hi: 4948307.5995 }, enrolled: { lo: 1140, hi: 2400 }, prestige: { lo: 50.178, hi: 84.5309 }, rank: { lo: 33, hi: 58.75 }, netMargin: { lo: 0.1276, hi: 0.2719 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 5398160.2015, hi: 23184834.5552 }, enrolled: { lo: 4500, hi: 10612.5 }, prestige: { lo: 52.0766, hi: 91.3898 }, rank: { lo: 27.75, hi: 51.25 }, netMargin: { lo: 0.1908, hi: 0.3758 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: 12431991.5629, hi: 113073098.5456 }, enrolled: { lo: 19980, hi: 37600 }, prestige: { lo: 97.6958, hi: 171.0433 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.0418, hi: 0.064 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 35, cash: { lo: 152859725.5759, hi: 357222592.8515 }, enrolled: { lo: 25140, hi: 41900 }, prestige: { lo: 112.0714, hi: 187.0236 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: 0.089, hi: 0.2183 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 50, cash: { lo: 232282488.4221, hi: 466607874.4265 }, enrolled: { lo: 25140, hi: 41900 }, prestige: { lo: 112.4876, hi: 187.4862 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: 0.4443, hi: 0.8613 }, weeksInTheRed: { lo: 0, hi: 10 } },
  ],
  "Curriculum rush (overreach)": [
    { year: 5, cash: { lo: 623914.9228, hi: 3433428.4083 }, enrolled: { lo: 482.25, hi: 1021.25 }, prestige: { lo: 29.554, hi: 53.1746 }, rank: { lo: 45.75, hi: 78.75 }, netMargin: { lo: -0.1067, hi: 0.0866 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: -6304039.8982, hi: 545570.1701 }, enrolled: { lo: 441, hi: 985 }, prestige: { lo: 30.779, hi: 57.7768 }, rank: { lo: 43.5, hi: 76.25 }, netMargin: { lo: 0.018, hi: 0.1916 }, weeksInTheRed: { lo: 54, hi: 222.5 } },
    { year: 20, cash: { lo: -7482815.4634, hi: 3453170.512 }, enrolled: { lo: 341.25, hi: 1486.25 }, prestige: { lo: 29.0788, hi: 61.5921 }, rank: { lo: 45, hi: 86.25 }, netMargin: { lo: -0.2027, hi: 0.2204 }, weeksInTheRed: { lo: 65.25, hi: 872.5 } },
    { year: 35, cash: { lo: -25003553.1375, hi: 5772047.3491 }, enrolled: { lo: 195, hi: 40600 }, prestige: { lo: 21.1738, hi: 149.1719 }, rank: { lo: 1, hi: 106.25 }, netMargin: { lo: -0.1544, hi: 0.4969 }, weeksInTheRed: { lo: 66, hi: 1847.5 } },
    { year: 50, cash: { lo: -45871341.1743, hi: 7574281946.2588 }, enrolled: { lo: 77, hi: 41900 }, prestige: { lo: 17.8675, hi: 186.3904 }, rank: { lo: 1, hi: 107.5 }, netMargin: { lo: -0.3219, hi: 0.4968 }, weeksInTheRed: { lo: 84, hi: 2822.5 } },
  ],
  "Discount volume (beds first)": [
    { year: 5, cash: { lo: -1661988.5752, hi: 487004.4124 }, enrolled: { lo: 420, hi: 700 }, prestige: { lo: 50.7688, hi: 84.6412 }, rank: { lo: 30, hi: 56.25 }, netMargin: { lo: -0.1426, hi: -0.0328 }, weeksInTheRed: { lo: 8, hi: 32 } },
    { year: 10, cash: { lo: -4278291.2099, hi: 490753.8999 }, enrolled: { lo: 420, hi: 700 }, prestige: { lo: 54.9505, hi: 93.3382 }, rank: { lo: 23.25, hi: 45 }, netMargin: { lo: -0.0151, hi: 0.1238 }, weeksInTheRed: { lo: 208.5, hi: 352.5 } },
    { year: 20, cash: { lo: -1589201.5983, hi: 2194838.0898 }, enrolled: { lo: 420, hi: 700 }, prestige: { lo: 56.5788, hi: 96.5056 }, rank: { lo: 22.5, hi: 42.5 }, netMargin: { lo: -0.0887, hi: 0.1353 }, weeksInTheRed: { lo: 263.25, hi: 757.5 } },
    { year: 35, cash: { lo: 1392526.4906, hi: 7404695.776 }, enrolled: { lo: 1140, hi: 5370 }, prestige: { lo: 45.7104, hi: 89.3792 }, rank: { lo: 27.75, hi: 63.75 }, netMargin: { lo: 0.0286, hi: 0.3651 }, weeksInTheRed: { lo: 263.25, hi: 882.5 } },
    { year: 50, cash: { lo: 3934720.5222, hi: 65710062.2952 }, enrolled: { lo: 6180, hi: 21500 }, prestige: { lo: 62.546, hi: 112.495 }, rank: { lo: 15.75, hi: 32.5 }, netMargin: { lo: -0.0564, hi: 0.0626 }, weeksInTheRed: { lo: 361.5, hi: 1135 } },
  ],
  "Completionist (build everything)": [
    { year: 5, cash: { lo: -298644.9505, hi: 3898679.9488 }, enrolled: { lo: 480, hi: 1400 }, prestige: { lo: 50.8824, hi: 86.3528 }, rank: { lo: 30, hi: 55 }, netMargin: { lo: -0.0726, hi: 0.1726 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: -525642.0475, hi: 6224776.6456 }, enrolled: { lo: 480, hi: 5800 }, prestige: { lo: 57.2477, hi: 103.8701 }, rank: { lo: 17.25, hi: 41.25 }, netMargin: { lo: -0.0205, hi: 0.3019 }, weeksInTheRed: { lo: 0, hi: 86.25 } },
    { year: 20, cash: { lo: 765687.166, hi: 46427456.2841 }, enrolled: { lo: 480, hi: 36400 }, prestige: { lo: 65.0981, hi: 159.114 }, rank: { lo: 1, hi: 22.5 }, netMargin: { lo: -0.0105, hi: 0.1414 }, weeksInTheRed: { lo: 0, hi: 86.25 } },
    { year: 35, cash: { lo: 12674033.3286, hi: 207189256.2831 }, enrolled: { lo: 5580, hi: 42200 }, prestige: { lo: 60.7062, hi: 186.6782 }, rank: { lo: 1, hi: 37.5 }, netMargin: { lo: 0.0395, hi: 0.3077 }, weeksInTheRed: { lo: 0, hi: 86.25 } },
    { year: 50, cash: { lo: 11370841.4263, hi: 326785958.6108 }, enrolled: { lo: 23820, hi: 42700 }, prestige: { lo: 109.9629, hi: 187.4762 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.0008, hi: 0.3584 }, weeksInTheRed: { lo: 0, hi: 97.5 } },
  ],
  "Overbuilder (beds ahead of demand)": [
    { year: 5, cash: { lo: -1386433.9863, hi: 1606455.6785 }, enrolled: { lo: 630.75, hi: 1170 }, prestige: { lo: 25.7925, hi: 50.0558 }, rank: { lo: 45.75, hi: 90 }, netMargin: { lo: -0.2811, hi: -0.0266 }, weeksInTheRed: { lo: 0, hi: 65 } },
    { year: 10, cash: { lo: -8595312.1164, hi: -463272.4703 }, enrolled: { lo: 357.75, hi: 877.5 }, prestige: { lo: 19.6272, hi: 43.4765 }, rank: { lo: 54, hi: 105 }, netMargin: { lo: -0.3305, hi: -0.0877 }, weeksInTheRed: { lo: 183.75, hi: 390 } },
    { year: 20, cash: { lo: -32952032.4987, hi: -6903656.9518 }, enrolled: { lo: 149, hi: 817.5 }, prestige: { lo: 16.5348, hi: 43.664 }, rank: { lo: 55.5, hi: 112.5 }, netMargin: { lo: -0.6284, hi: -0.0568 }, weeksInTheRed: { lo: 573.75, hi: 1040 } },
    { year: 35, cash: { lo: -64993983.792, hi: -12144677.8429 }, enrolled: { lo: 52, hi: 422 }, prestige: { lo: 9.3758, hi: 30.0123 }, rank: { lo: 66, hi: 120 }, netMargin: { lo: -0.3375, hi: -0.1599 }, weeksInTheRed: { lo: 1158.75, hi: 2015 } },
    { year: 50, cash: { lo: -80393508.7583, hi: -17655246.6305 }, enrolled: { lo: 70, hi: 520 }, prestige: { lo: 10.4494, hi: 32.3144 }, rank: { lo: 66, hi: 121.25 }, netMargin: { lo: -0.3921, hi: -0.0206 }, weeksInTheRed: { lo: 1743.75, hi: 2990 } },
  ],
  "Earnest completionist": [
    { year: 5, cash: { lo: 2821231.5899, hi: 5497237.2481 }, enrolled: { lo: 1320, hi: 2600 }, prestige: { lo: 50.7396, hi: 85.4281 }, rank: { lo: 30, hi: 53.75 }, netMargin: { lo: 0.2396, hi: 0.4165 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 12425978.0408, hi: 36684775.0772 }, enrolled: { lo: 8940, hi: 17100 }, prestige: { lo: 58.2983, hi: 98.4295 }, rank: { lo: 17.25, hi: 35 }, netMargin: { lo: 0.1882, hi: 0.3406 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: 6789482.9733, hi: 139441930.6577 }, enrolled: { lo: 20580, hi: 42600 }, prestige: { lo: 104.3806, hi: 177.6702 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.01, hi: 0.1095 }, weeksInTheRed: { lo: 0, hi: 82.5 } },
    { year: 35, cash: { lo: 77239078.261, hi: 385112948.298 }, enrolled: { lo: 25140, hi: 42700 }, prestige: { lo: 112.2649, hi: 187.2154 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: 0.0648, hi: 0.649 }, weeksInTheRed: { lo: 0, hi: 82.5 } },
    { year: 50, cash: { lo: 190597135.6053, hi: 477956107.7837 }, enrolled: { lo: 25140, hi: 42700 }, prestige: { lo: 112.4932, hi: 187.4918 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: 0.3796, hi: 2.0018 }, weeksInTheRed: { lo: 0, hi: 82.5 } },
  ],
  "Scatterer (founds anything anywhere)": [
    { year: 5, cash: { lo: 3288105.8435, hi: 5854101.9149 }, enrolled: { lo: 1784.25, hi: 3000 }, prestige: { lo: 46.0509, hi: 84.098 }, rank: { lo: 33, hi: 63.75 }, netMargin: { lo: 0.1749, hi: 0.5023 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 6734347.7232, hi: 24572153.9227 }, enrolled: { lo: 6873, hi: 14451.25 }, prestige: { lo: 52.658, hi: 96.5684 }, rank: { lo: 21, hi: 47.5 }, netMargin: { lo: 0.1834, hi: 0.4262 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: 41999961.7627, hi: 206724067.1012 }, enrolled: { lo: 20580, hi: 34300 }, prestige: { lo: 75.6029, hi: 135.9748 }, rank: { lo: 1, hi: 9 }, netMargin: { lo: 0.0138, hi: 0.1286 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 35, cash: { lo: 105515204.7951, hi: 218448431.6071 }, enrolled: { lo: 20580, hi: 34300 }, prestige: { lo: 79.8724, hi: 144.8065 }, rank: { lo: 1, hi: 8 }, netMargin: { lo: 0.1533, hi: 0.4287 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 50, cash: { lo: 134338191.0996, hi: 244456201.8794 }, enrolled: { lo: 20580, hi: 34300 }, prestige: { lo: 81.6666, hi: 146.503 }, rank: { lo: 1, hi: 8 }, netMargin: { lo: 0.3753, hi: 0.8676 }, weeksInTheRed: { lo: 0, hi: 10 } },
  ],
  "Selective college": [
    { year: 5, cash: { lo: 1645177.2117, hi: 4806541.1691 }, enrolled: { lo: 729, hi: 1698.75 }, prestige: { lo: 50.3554, hi: 96.7451 }, rank: { lo: 22.5, hi: 55 }, netMargin: { lo: 0.3878, hi: 0.8674 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 3439271.5989, hi: 11779566.0168 }, enrolled: { lo: 2766, hi: 6798.75 }, prestige: { lo: 59.7755, hi: 111.6081 }, rank: { lo: 7, hi: 31.25 }, netMargin: { lo: 0.3065, hi: 0.725 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: 28130777.9346, hi: 59352023.6735 }, enrolled: { lo: 3123.75, hi: 5393.75 }, prestige: { lo: 105.0476, hi: 179.068 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.0506, hi: 0.0675 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 35, cash: { lo: 26995818.7405, hi: 56960127.2651 }, enrolled: { lo: 2928, hi: 5011.25 }, prestige: { lo: 112.2842, hi: 187.2559 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: 0.2792, hi: 0.4981 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 50, cash: { lo: 17658003.1448, hi: 42782300.0409 }, enrolled: { lo: 2979, hi: 5015 }, prestige: { lo: 112.4938, hi: 187.4929 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: 0.5186, hi: 1.2236 }, weeksInTheRed: { lo: 0, hi: 10 } },
  ],
  "Regional engine": [
    { year: 5, cash: { lo: 3289874.1551, hi: 6071133.2135 }, enrolled: { lo: 1500, hi: 2900 }, prestige: { lo: 47.7287, hi: 83.2329 }, rank: { lo: 32.25, hi: 63.75 }, netMargin: { lo: 0.2491, hi: 0.4786 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 11386230.0577, hi: 45736663.6948 }, enrolled: { lo: 7500, hi: 23908.75 }, prestige: { lo: 55.93, hi: 103.2938 }, rank: { lo: 14.25, hi: 36.25 }, netMargin: { lo: 0.1434, hi: 0.3334 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: 10452292.7911, hi: 107141996.2311 }, enrolled: { lo: 18420, hi: 40700 }, prestige: { lo: 92.0977, hi: 178.8177 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.019, hi: 0.1019 }, weeksInTheRed: { lo: 0, hi: 171.25 } },
    { year: 35, cash: { lo: 74273717.937, hi: 354730925.8514 }, enrolled: { lo: 24840, hi: 42300 }, prestige: { lo: 111.5601, hi: 187.2486 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: -0.0007, hi: 0.1166 }, weeksInTheRed: { lo: 0, hi: 171.25 } },
    { year: 50, cash: { lo: 221185913.5053, hi: 377608202.5929 }, enrolled: { lo: 25140, hi: 42300 }, prestige: { lo: 112.4728, hi: 187.4927 }, rank: { lo: 1, hi: 4 }, netMargin: { lo: 0.0364, hi: 0.1894 }, weeksInTheRed: { lo: 0, hi: 171.25 } },
  ],
  "Idle (builds nothing)": [
    { year: 5, cash: { lo: 4605841.3217, hi: 7686955.9407 }, enrolled: { lo: 337.5, hi: 565 }, prestige: { lo: 30.911, hi: 51.5426 }, rank: { lo: 45, hi: 80 }, netMargin: { lo: 0.0328, hi: 0.1336 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 10, cash: { lo: 5839367.003, hi: 9949469.5709 }, enrolled: { lo: 337.5, hi: 562.5 }, prestige: { lo: 29.4071, hi: 51.6597 }, rank: { lo: 45.75, hi: 83.75 }, netMargin: { lo: 0.0368, hi: 0.1418 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 20, cash: { lo: 9044835.9907, hi: 17836286.2571 }, enrolled: { lo: 287, hi: 563.75 }, prestige: { lo: 26.1384, hi: 52.3164 }, rank: { lo: 49.5, hi: 93.75 }, netMargin: { lo: 0.0706, hi: 0.2742 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 35, cash: { lo: 18322454.0391, hi: 35195892.2172 }, enrolled: { lo: 16, hi: 296 }, prestige: { lo: 15.0123, hi: 36.8801 }, rank: { lo: 58.5, hi: 115 }, netMargin: { lo: 0.2408, hi: 0.574 }, weeksInTheRed: { lo: 0, hi: 10 } },
    { year: 50, cash: { lo: 28327477.9465, hi: 52999370.4641 }, enrolled: { lo: 34, hi: 506.25 }, prestige: { lo: 17.6427, hi: 44.6446 }, rank: { lo: 59.25, hi: 113.75 }, netMargin: { lo: 0.3683, hi: 0.6489 }, weeksInTheRed: { lo: 0, hi: 10 } },
  ],
};
// --- END GENERATED ---
